shell = "fish -c '{}'"
default-scheme = "base16-eva01"

[[items]]
name = "oomox"
path = "~/dev/colorschemes/base16"
themes-dir = "schemes"
hook = "cp -f %f ~/.config/oomox/colors/__plugin__base16/system.yml"
theme-file-extension = ".yml"

[[items]]
name = "gtk2-flatcolor"
path = "~/dev/colorschemes/gtk-flatcolor"
themes-dir = "gtk-2"
hook = "cp -f %f ~/.themes/FlatColor/colors2"
theme-file-extension = "-gtkrc"

[[items]]
name = "gtk3-flatcolor"
path = "~/dev/colorschemes/gtk-flatcolor"
themes-dir = "gtk-3"
hook = "cp -f %f ~/.themes/FlatColor/colors3.css"
theme-file-extension = "-gtk.css"

[[items]]
name = "qt5ct-conf"
path = "~/dev/colorschemes/qt5ct"
themes-dir = "qt5ct_appearance_conf"
hook = "cp -f %f ~/.config/qt5ct/qt5ct.conf"
theme-file-extension = ".conf"

[[items]]
name = "qt5ct-colors"
path = "~/dev/colorschemes/qt5ct"
themes-dir = "colors"
hook = "cp -f %f ~/.config/qt5ct/colors/colors.conf"
theme-file-extension = ".conf"

[[items]]
name = "zathura"
path = "~/dev/colorschemes/zathura"
themes-dir = "colors"
hook = "cp -f %f ~/.config/zathura/zathurarc"
theme-file-extension = ""

[[items]]
name = "tmux"
path = "~/dev/colorschemes/tmux"
themes-dir = "colors"
hook = "cp -f %f ~/.config/tmux/colors.tmux.conf"
theme-file-extension = ".tmux.conf"

[[items]]
name = "fish"
path = "~/dev/colorschemes/fish"
themes-dir = "functions"
hook = "cp -f %f ~/.config/fish/functions/base16_colors.fish"
theme-file-extension = ".fish"

[[items]]
name = "nvim-mini.base16"
path = "~/dev/colorschemes/nvim/mini.base16"
themes-dir = "colors"
hook = "cp -f %f ~/.config/nvim/lua/plugins/base16.lua"
theme-file-extension = ".lua"

[[items]]
name = "ghostty"
path = "~/dev/colorschemes/ghostty"
themes-dir = "colors"
hook = "cp -f %f ~/.config/ghostty/themes/system"

[[items]]
name = "helix"
path = "~/dev/colorschemes/helix"
themes-dir = "themes"
hook = "cp -f %f ~/.config/helix/themes/system.toml"
theme-file-extension = ".toml"

[[items]]
name = "mako"
path = "~/dev/colorschemes/mako"
themes-dir = "colors"
hook = "cp -f %f ~/.config/mako/config"

[[items]]
name = "aerc"
path = "~/dev/colorschemes/aerc"
themes-dir = "stylesets"
hook = "cp -f %f ~/.config/aerc/stylesets/system"

[[items]]
name = "gtk4"
path = "~/dev/colorschemes/gtk4"
themes-dir = "colors"
hook = "cp -f %f ~/.config/gtk-4.0/gtk.css"
theme-file-extension = ".css"

[[items]]
name = "bemenu"
path = "~/dev/colorschemes/bemenu"
themes-dir = "scripts"
hook = "cp -f %f ~/scripts/pinentry_wrapper && chmod +x ~/scripts/pinentry_wrapper"
theme-file-extension = ".sh"
